name: Build & Push to ECR
on:
  push:
    branches: [ main ]          # 以后推 main 就触发

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write           # OIDC 必需
      contents: read

    steps:
    - uses: actions/checkout@v4

    # ① OIDC 登录 AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}

    # ② 登录 ECR
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ${{ vars.AWS_REGION }} | \
        docker login --username AWS --password-stdin 767397885675.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

    # ③ Build & Push
      # 镜像 tag 用 commit SHA，可保留唯一性
    - name: Build, tag, and push
      run: |
        IMAGE_URI=767397885675.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/bazifegnshui/main:${{ github.sha }}
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    # ④ 可选：同步 latest 标签
    - name: Move latest tag
      run: |
        MANIFEST=$(aws ecr batch-get-image --repository-name bazifegnshui/main \
                   --image-ids imageTag=${{ github.sha }} \
                   --query 'images[0].imageManifest' --output text)
        aws ecr put-image --repository-name bazifegnshui/main \
          --image-tag latest --image-manifest "$MANIFEST"
