name: Build & Push to ECR
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials   # <-- 登录
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ${{ vars.AWS_REGION }} | \
        docker login -u AWS --password-stdin 767397885675.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

    - name: Build & Push
      env: { IMAGE_TAG: ${{ github.sha }} }
      run: |
        IMAGE_URI=767397885675.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/bazifegnshui/main:$IMAGE_TAG
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

